- name: Publicar na Cloudflare
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      run: |
        # Remove pastas de cache para garantir que nada antigo interfira
        rm -rf .wrangler
        
        # Executa o deploy garantindo que o Wrangler utilize o token e o ID de conta
        npx wrangler deploy --name assinatura-partido-mjp --account-id $CLOUDFLARE_ACCOUNT_ID
